name: canonical-fasta
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy<2.0
  - requests
  - biopython
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - tqdm
  - umap-learn
  - jax
  - jaxlib
  - pip
  - pip:
      - torch
      - 'transformers>=4.29.0'
      - einops
      - gtfparse
      - pyfaidx
      - dm-haiku
